### ISSUE TITLE
Deprecated "rnpm" config

### ISSUE THREAD

**Issue by kurbanovjasur** [WrathChaos/react-native-bouncy-checkbox#10]
I got this kind of warning. Thought it would be better to inform maintainers about it.

The following packages use deprecated "rnpm" config that will stop working from next release:
  - react-native-bouncy-checkbox: https://www.freakycoder.com
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.

**Comment by WrathChaos** [comment]
I will resolve it ASAP :) Thank you @kurbanovjasur

**Comment by WrathChaos** [comment]
@kurbanovjasur I've published a new version: [0.1.3](https://github.com/WrathChaos/react-native-bouncy-checkbox/releases/tag/0.1.3)

Please check this out and give me a feedback that bug is fixed or not :)
