### ISSUE TITLE
not able to change icon .

### ISSUE THREAD

**Issue by th1copycatninja** [WrathChaos/react-native-bouncy-checkbox#106]
really loved your library but i want to change the icon but not able to change. i also used checkIconImageSource , iconComponent also, can you please help.

**Comment by WrathChaos** [comment]
Hello @th1copycatninja,
You can directly use `iconComponent` to set any component instead of the default check image component.

Something like this:
```jsx
<BouncyCheckbox 
   iconComponent={<Image source={} style={} />}
   onPress={(isChecked: boolean) => {}} 
/>
```

**Comment by th1copycatninja** [comment]
thanks its worked.
