### ISSUE TITLE
Color of checked icon

### ISSUE THREAD

**Issue by teckbeng-payboy** [WrathChaos/react-native-bouncy-checkbox#107]
May I know is there any props for me to change the color of checked icon? This is due to the background color of my checkbox will be white in color

**Comment by WrathChaos** [comment]
Hello @teckbeng-payboy 
You can override the default icon style with `iconImageStyle` prop. So you can use `tintColor` to change the icon's color. 

OR

you can use `iconComponent` prop to set your own icon component as you wish. 


Something like this:
```jsx
<BouncyCheckbox 
   iconComponent={<Image source={} style={} />}
   onPress={(isChecked: boolean) => {}} 
/>
```

**Comment by teckbeng-payboy** [comment]
I'm sorry, is there `iconImageStyle` prop?

You mean like this 

`<BouncyCheckbox 
   iconImageStyle={styles.xxx}
   onPress={(isChecked: boolean) => {}} 
/>`
