### ISSUE TITLE
How to move text on left

### ISSUE THREAD

**Issue by Pippouz** [WrathChaos/react-native-bouncy-checkbox#110]
It is possible to move the text of the checkbox to left, obviously with checkbox on right?

**Comment by WrathChaos** [comment]
Hello @Pippouz 
By default, we don't have that kind of support. However, you can use `disableText` prop to disable the right text and put a text by yourselves and handle it :) 

The library is all customizable. If you need help to do that, please write me down ;)

**Comment by Pippouz** [comment]
> Hello @Pippouz 
> By default, we don't have that kind of support. However, you can use `disableText` prop to disable the right text and put a text by yourselves and handle it :) 
> 
> The library is all customizable. If you need help to do that, please write me down ;) 

ok, thanks for the info

**Comment by Pippouz** [comment]
> Hello @Pippouz 
> By default, we don't have that kind of support. However, you can use `disableText` prop to disable the right text and put a text by yourselves and handle it :) 
> 
> The library is all customizable. If you need help to do that, please write me down ;) 

ok, thanks for the info

**Comment by likhit-vivek** [comment]
you can also do this for bringing text to the left:
```<BouncyCheckbox style={{ flex: 1, flexDirection: "row-reverse" }} />```
