### ISSUE TITLE
Issue with the advanced custom example given in the readme

### ISSUE THREAD

**Issue by Exhigh** [WrathChaos/react-native-bouncy-checkbox#124]
https://github.com/WrathChaos/react-native-bouncy-checkbox#advanced-custom-usage

```
<BouncyCheckbox
  size={25}
  fillColor="red"
  unfillColor="#FFFFFF"
  text="Custom Checkbox"
  iconStyle={{ borderColor: "red" }}
  iconInnerStyle={{ borderWidth: 2 }} <----------- The style type is the wrong style type as it should be innerIconStyle.
  textStyle={{ fontFamily: "JosefinSans-Regular" }}
  onPress={(isChecked: boolean) => {}}
/>
```

**Comment by WrathChaos** [comment]
Hello @Exhigh 
Ah thank you so much for reporting this issue. 

I forgot to change the old examples :D I will update it now

**Comment by WrathChaos** [comment]
https://github.com/WrathChaos/react-native-bouncy-checkbox/commit/baa208a29fcd91306603a4fc68734e6d02a14bb8

Thank you so much :)
