### ISSUE TITLE
Nested items

### ISSUE THREAD

**Issue by plainspace** [WrathChaos/react-native-bouncy-checkbox#131]
Hey there! Have you thought about implementing nested items?

**Comment by WrathChaos** [comment]
Hello @plainspace 
Can you explain what do you mean by nested items? Can you give an example?

**Comment by plainspace** [comment]
Basically being able to drag a list item into/onto a top level list item. 

![image](https://user-images.githubusercontent.com/24152/184862066-4c4c6022-0499-42fc-92e9-1d47828e1faf.jpeg)

**Comment by plainspace** [comment]
Going to close the issue. Realized that it isn't relevant.

**Comment by WrathChaos** [comment]
Actually this is do-able with a custom solution :) You can use your own state management for checkboxes. 
Take a look at [this](https://github.com/WrathChaos/react-native-bouncy-checkbox#synthetic-press-functionality-with-manual-check-state)
