### ISSUE TITLE
how to change unfill icon style round to square

### ISSUE THREAD

**Issue by partTimeCoder96** [WrathChaos/react-native-bouncy-checkbox#133]
<BouncyCheckbox
                  size={25}
                  fillColor={colors.nightRider}
                  unfillColor="#FFFFFF"
                   iconStyle={{ borderColor:colors.nightRider,borderRadius:2 }}
                  //  iconInnerStyle={{ height:240,borderRadius:2 }}
                  onPress={(isChecked: boolean) => {}}
                  useNativeDriver={true}
                  style={{borderColor:colors.nightRider,borderRadius:2}}
                />

fill icon changed to the square but not for unfill, the icon style again went to a round shape how to keep only a square shape.
style property also not working.

**Comment by partTimeCoder96** [comment]
![IMG_0047](https://user-images.githubusercontent.com/33393692/186657431-67f658a5-9af5-47c6-8d59-9c1f0ecf7652.PNG)
![IMG_0046](https://user-images.githubusercontent.com/33393692/186657448-0716aecf-a866-442a-b49c-0538feab9e73.PNG)

**Comment by WrathChaos** [comment]
Hello @partTimeCoder96 ,
Can you please use `innerIconStyle` instead of `iconInnerStyle`.
Probably this will fix your issue

**Comment by partTimeCoder96** [comment]
yes, it's fixed thanks.
