### ISSUE TITLE
onPress TS Error  

### ISSUE THREAD

**Issue by omniviewsports** [WrathChaos/react-native-bouncy-checkbox#157]
@WrathChaos

I have a login screen (see below for source code) where I am disabling a login button until the user accepts a EULA agreement by clicking the checkbox. The code works, but I get the following TS error:

Type 'boolean | (() => void)' is not assignable to type '((checked: boolean) => void) | undefined'.
Type 'boolean' is not assignable to type '(checked: boolean) => void'.

Any advice on how I can fix this?
```
//useToggle.ts
import { useCallback, useState } from "react";
export const useToggle = (initialState = false) => {
  const [state, setState] = useState(initialState);
  const toggle = useCallback(() => setState((prevState) => !prevState), []);
  return [state, toggle];
};

```

```
//LoginScreen.tsx
export const LoginScreen = (): JSX.Element => {
  const [termsAccepted, setTermsAccepted] = useToggle();
  return (
    <View.Safe style={loginScreenStyles.container} edges={["left", "right"]}>
      <View.Column style={loginScreenStyles.loginContainer}>
        {constants.auth.welcomeText}

        <View.Row></View.Row>
      </View.Column>
    </View.Safe>
  );
};
```

**Comment by WrathChaos** [comment]
Hello @omniviewsports 
Thank you for using the library :) 

Actually I cannot even see the usage of `react-native-bouncy-checkbox` in the example code. Do I miss anything?

**Comment by omniviewsports** [comment]
@WrathChaos (sorry, for some reason that part did not paste - here is the code).

import BouncyCheckbox from 'react-native-bouncy-checkbox';
import { View, Text } from 'components';
import { useToggle } from 'handlers';
import { constants } from 'config';
import { LoginHeader, LoginButton, EulaAgreement } from './elements';
import { loginScreenStyles } from './styles';
import { onLogin } from './logic';

//TODO: [YZ-148] Find Fix for Bouncy Checkbox TS Error
//TODO: [YZ-150] Clean up checkbox & EULA agreement styles
export const LoginScreen = (): JSX.Element => {
  const [termsAccepted, setTermsAccepted] = useToggle({ initialState: false });

  return (
    <View.Safe style={loginScreenStyles.container} edges={['left', 'right']}>
      <LoginHeader />
      <View.Column style={loginScreenStyles.loginContainer}>
        <Text style={loginScreenStyles.tagline}>{constants.auth.welcomeText}</Text>
        <LoginButton onPress={onLogin} disabled={!termsAccepted} />
        <View.Row style={loginScreenStyles.eula}>
          {/* @ts-expect-error - setTermsAccepted works but need to create a TS fix*/}
          <BouncyCheckbox onPress={setTermsAccepted} size={12} />
          <EulaAgreement />
        </View.Row>
      </View.Column>
    </View.Safe>
  );
};

**Comment by WrathChaos** [comment]
@omniviewsports I am sorry but I will not download this file because of security reasons :)

**Comment by omniviewsports** [comment]
@WrathChaos for some reason, when I paste the source code, the BouncyCheckBox component does not show up.
Accordingly, the parameters I pass to the component are

- onPress{setTermsAccepted}
- size={12}

The component is wrapped by a View and followed by a text component that recites the EULA agreement.

**Comment by WrathChaos** [comment]
Hmm, I guess I got it why you're having this error. It is because `react-native-bouncy-checkbox` has its own check state system built-in. 

You want to control it with `useToggle` hook. So you need to use `disableBuiltInState` props to control your own whole check system for the checkbox button :) 

Please check this doc part: 
https://github.com/WrathChaos/react-native-bouncy-checkbox#synthetic-press-functionality-with-manual-check-state

You will see how to use it. Also, there is a separated example for this one either.
