### ISSUE TITLE
Checkbox doesnt work on android emulator (React native 0.69.6)

### ISSUE THREAD

**Issue by MordechaiCharlap** [WrathChaos/react-native-bouncy-checkbox#161]
![image](https://user-images.githubusercontent.com/74620228/196192923-7543a3fd-c18c-4ae3-ae21-e03c6d2bde81.png)
As you can see on the emulator I get error, terminal says :
› Reloading apps
Android Bundling failed 8ms
Unable to resolve "react-native-bouncy-checkbox" from "screens\LoginScreen.js"

 while on the web its working fine and shows in the UI

**Comment by WrathChaos** [comment]
Hello @MordechaiCharlap 

Thank you for reporting the issue, I am checking right now :)

**Comment by WrathChaos** [comment]
Hey again @MordechaiCharlap 
I tried to run the `example` app on android it works without any issue. Can you try the example project please?

**Comment by MordechaiCharlap** [comment]
Hey @WrathChaos , thanks for the fast reply :)
actually just downloaded the example and haven`t managed to open it.. a lot of errors I'm not sure why..
I already made checkbox component by myself, if it works for you I guess it's a problem just for me..
But maybe you should update the react native before you try just to make sure (I see that the react native version in the example is 0.69.2 and in main it's 0.69.6, btw now there is already 0.70 at least)

**Comment by WrathChaos** [comment]
I'm using this library multiple projects and multiple react-native versions which includes latest RN version 0.70+. I could not reproduce your issue.

Can you show me your issues with the example one? Example is extremely simple project.
