### ISSUE TITLE
Property isChecked is not working

### ISSUE THREAD

**Issue by yasmany993** [WrathChaos/react-native-bouncy-checkbox#180]
When using 
< BouncyCheckbox
      size={20}
      isChecked={true}
  />
component is not being checked

**Comment by yasmany993** [comment]
Opened by mistake, component works as expected

**Comment by ViktorVojtek** [comment]
@yasmany993 I've encountered a similar issue, but only on real device iPhone 7. On simulator or other devices this works as expected. Do you have similar results or more information you can share?

**Comment by WrathChaos** [comment]
Hello @ViktorVojtek 
I don't know your use-cases for using the library but probably you want to control the state by yourself. 

Please check this documentation: 

https://github.com/WrathChaos/react-native-bouncy-checkbox#synthetic-press-functionality-with-manual-check-state
