### ISSUE TITLE
Missing fonts when using the following package.json settings

### ISSUE THREAD

**Issue by ascooper57** [WrathChaos/react-native-bouncy-checkbox#2]
"react": "16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
    "react-native-bottom-search-bar": "0.0.24",
    "react-native-bouncy-checkbox": "0.0.2",
    "react-native-dynamic-vector-icons": "^0.2.1",
    "react-native-iphone-x-helper": "^1.2.1",
    "react-native-vector-icons": "^6.6.0",

// =================================================================
Also in App.js I had to add:
async function loadResourcesAsync() {
  await Promise.all([
    Font.loadAsync({
      // This is the font that we are using for our Checkboxes
      'Entypo': require('./assets/fonts/Entypo/entypo.ttf'),
      'JosefinSans-Regular': require('./assets/fonts/JosefinSans/JosefinSans-Regular.ttf'),
    }),
  ]);
}

[fonts.zip](https://github.com/WrathChaos/react-native-bouncy-checkbox/files/3870362/fonts.zip)

**Comment by WrathChaos** [comment]
Hello,
I'm gonna fix you right now, so sorry just forget to remove fontFamily part :)

**Comment by WrathChaos** [comment]
Hi again @ascooper57,
I've fixed and released a new version. Please check it out: 

## [Release 0.0.3  🤩😘](https://github.com/WrathChaos/react-native-bouncy-checkbox/releases/tag/0.0.3)
