### ISSUE TITLE
Unrecognised font family

### ISSUE THREAD

**Issue by faraz-ahmad-uft** [WrathChaos/react-native-bouncy-checkbox#207]
When we installed the plugin, we got following error. Followed the same steps which are mentioned in the doc. We deleted node_modules, reset cache but nothing worked.
![Simulator Screen Shot - iPhone 14 - 2023-01-26 at 13 48 56](https://user-images.githubusercontent.com/110594522/214788406-3209493d-154d-42af-a331-b74346e013f3.png)

Our package.json file.
<img width="497" alt="Screenshot 2023-01-26 at 1 51 49 PM" src="https://user-images.githubusercontent.com/110594522/214788604-befadafb-ff10-4514-944c-abdce9d8bb94.png">

**Comment by WrathChaos** [comment]
Hellooo
Thank you for reaching me and using the library :) 
Let me take a look at it very fast

**Comment by WrathChaos** [comment]
@faraz-ahmad-uft 
Can you also show me the code how to use the `react-native-bouncy-checkbox` ?

**Comment by faraz-ahmad-uft** [comment]
@WrathChaos - Following were my step.
1. I run **npm i react-native-bouncy-checkbox** command for installing it.
2. Added **import BouncyCheckbox from "react-native-bouncy-checkbox";** in the imports.
3. Added <BouncyCheckbox
  size={25}
  fillColor="red"
  unfillColor="#FFFFFF"
  text="Custom Checkbox"
  iconStyle={{ borderColor: "red" }}
  innerIconStyle={{ borderWidth: 2 }}
  textStyle={{ fontFamily: "JosefinSans-Regular" }}
  onPress={(isChecked: boolean) => {}}
/>
4. Clean the project and run again.

Do you need any other details. Please let me know.

**Comment by WrathChaos** [comment]
You need to remove `textStyle`. It is just an example that you can customize the font family.

I tested on the example folder and also created a fresh project. It works all fine :)

**Comment by faraz-ahmad-uft** [comment]
@WrathChaos  Thanks for your time.
