### ISSUE TITLE
How to disable checkbox?

### ISSUE THREAD

**Issue by edwinwong90** [WrathChaos/react-native-bouncy-checkbox#21]
Hi WrathChaos,

At first, This is very nice component! After using it kinda like it. But How I can disable the checkbox like others common checkbox library do, like provide disable props?

**Comment by WrathChaos** [comment]
Hello @edwinwong90 
I've added the all TouchableOpacity props availability :) You can use `disabled` prop for disable the Checkbox.

Please check the new version 

### [Release 1.0.8 🥳](https://github.com/WrathChaos/react-native-bouncy-checkbox/releases/tag/1.0.8)

**Comment by edwinwong90** [comment]
Hi @WrathChaos, just try out. It works! thanks!

**Comment by WrathChaos** [comment]
If you need anything please open an issue :)

**Comment by idanlevi1** [comment]
> Hello @edwinwong90 I've added the all `TouchableOpacity` props availability :) You can use `disabled` prop for disable the Checkbox.
> 
> Please check the new version
> 
> ### [Release 1.0.8 🥳](https://github.com/WrathChaos/react-native-bouncy-checkbox/releases/tag/1.0.8)

@WrathChaos 
It's work, but I can use it because `disabled` is not defined in props type...can you add it?
