### ISSUE TITLE
tintColor is not assignable to iconImageStyle prop

### ISSUE THREAD

**Issue by DaLukasTI** [WrathChaos/react-native-bouncy-checkbox#221]
When setting tintColor on the iconImageStyle prop typescript throws an error, but it does work in app so it's probably just a TS thing.

error:

`Type '{ tintColor: string; }' is not assignable to type 'CustomStyleProp'.
  Object literal may only specify known properties, and 'tintColor' does not exist in type 'ViewStyle | RecursiveArray<ViewStyle | Falsy | RegisteredStyle<ViewStyle>> | StyleProp<ViewStyle>[]'.ts(2322)
BouncyCheckbox.d.ts(31, 5): The expected type comes from property 'iconImageStyle' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<BouncyCheckbox> & Readonly<IBouncyCheckboxProps>'`

**Comment by abdemirza** [comment]
I have resolved this issue, thank you.

**Comment by WrathChaos** [comment]
Hey @DaLukasTI 
Sorry for the late response. 

I will release a new version to fix this TS problem. Thank you for reporting this :)

**Comment by WrathChaos** [comment]
> 

Unfortunately, this comment does not help at all. If you resolved this, please open a PR to contribute the open source.

**Comment by WrathChaos** [comment]
> I have resolved this issue, thank you.

You should have told that there is a PR for this :D Thank you! 

I will release a new version for this today

**Comment by WrathChaos** [comment]
#224 Merged, will release a version today!

**Comment by abdemirza** [comment]
> You should have told that there is a PR for this :D Thank you! 

Noted, will make sure about this in the next issue :D

**Comment by WrathChaos** [comment]
[Version 3.0.7 🎃](https://github.com/WrathChaos/react-native-bouncy-checkbox/releases/tag/3.0.7) is released :) 

Thank you @abdemirza 

@DaLukasTI please check it out :)
