### ISSUE TITLE
react-native compatibility

### ISSUE THREAD

**Issue by Benetzz** [WrathChaos/react-native-bouncy-checkbox#27]
Hi, what are the react-native versions supported? 

Thanks

**Comment by WrathChaos** [comment]
Hello @Benetzz,
It should work after 0.55+ but have not tried that below. I'm sure that it should work 0.60+

**Comment by Benetzz** [comment]
Thanks @WrathChaos. I I have the chance I will try it with the 0.58 and give you feedback.

**Comment by WrathChaos** [comment]
If you have a problem with 0.58, I can make it compatible if it is possible :)
