### ISSUE TITLE
Refactoring the library for 2.0 version

### ISSUE THREAD

**Issue by WrathChaos** [WrathChaos/react-native-bouncy-checkbox#28]
- Cleaning the ugly code
- Refactoring the logics
- 1.5 version is on the way

**Comment by mariomurrent-softwaresolutions** [comment]
Really nice work - looking forward to the new version

**Comment by WrathChaos** [comment]
EDIT: **2.0** version is incoming with better customization and better coding.

**Comment by mariomurrent-softwaresolutions** [comment]
Nice, thx

**Comment by WrathChaos** [comment]
[Version 2.0.0 is alive  🥳](https://github.com/WrathChaos/react-native-bouncy-checkbox/releases/tag/2.0.0)
