### ISSUE TITLE
Use like radio buttons

### ISSUE THREAD

**Issue by marcoslucianops** [WrathChaos/react-native-bouncy-checkbox#29]
Can I use this checkbox like radio buttons? I'm trying to uncheck checkbox when another one is checked. Is it possible?

**Comment by WrathChaos** [comment]
Hello @marcoslucianops,
Yes of course you can, here is how to do it?
https://github.com/WrathChaos/react-native-animated-radio-button-group

Simply look at the lib code :) If you cannot do it, we can do it together

**Comment by marcoslucianops** [comment]
I don't' know how to do this, can you help me? How can I set a property to check/uncheck with state like below code?

```
<BouncyCheckbox
  check={firstRadio}
  textColor="#000"
  size={20}
  borderColor="#8c66af"
  fillColor="#8c66af"
  textDecoration={true}
  text="Morador"
  onPress={(checked) => {
    setFirstRadio(checked);
    setSecondRadio(!checked);
  }}
/>
<BouncyCheckbox
  check={secondRadio}
  textColor="#000"
  size={20}
  borderColor="#8c66af"
  fillColor="#8c66af"
  textDecoration={true}
  text="Morador"
  onPress={(checked) => {
    setSecondRadio(checked);
    setFirstRadio(!checked);
  }}
/>
```
I will use only 2 checkboxes.

Thanks.

**Comment by WrathChaos** [comment]
I will create an example of how to do it

**Comment by marcoslucianops** [comment]
I managed to make it works. Thanks.

**Comment by juanyaguaro** [comment]
Hi @marcoslucianops ! I'm in a similar situation, could you explain how did you make it work? Thanks!

**Comment by marcoslucianops** [comment]
@juanyaguaro, I created a radio, controlled by state, based on this checkbox style.

**Comment by awedev** [comment]
How can you get it working, the library does not expose internal state, the check mark won't display properly

**Comment by WrathChaos** [comment]
@awedev The library exposes the current `isChecked` state. 

Here is the example: 

```
<BouncyCheckbox
   size={25}
   fillColor="red"
   unfillColor="#FFFFFF"
   text="Custom Checkbox"
   onPress={(isChecked: boolean) => console.log("isChecked State", isChecked) }
 />
```

**Comment by awedev** [comment]
@WrathChaos thanks for your reply, but the ask is to use it as a radio button. The state passed in onPress won't work, because you can't control the state.

For example, you have two checkboxes, and you want to select one of them and uncheck the other, how do you do uncheck the other without exposing the state? The existing properly isChecked is only for initial value.

**Comment by WrathChaos** [comment]
@awedev 

Did you investigate this one?

https://github.com/WrathChaos/react-native-animated-radio-button-group
