### ISSUE TITLE
Unable to resolve module `@freakycoder/react-native-helpers`

### ISSUE THREAD

**Issue by Grishy** [WrathChaos/react-native-bouncy-checkbox#3]
Hi,

Try to start example and get:
![image](https://user-images.githubusercontent.com/13949080/70865003-402dca00-1f0d-11ea-87af-850bcc224ed8.png)

**Comment by Grishy** [comment]
Just need add dep to example

**Comment by WrathChaos** [comment]
You're right, I've missed that dependency. Actually it is NOT for this library's dependency just for the better design example :) I'm updating the repo now.

**Comment by WrathChaos** [comment]
@Grishy I've updated the example :) Thank you so much.
