### ISSUE TITLE
Triggering Synthetic onPress

### ISSUE THREAD

**Issue by bramirez96** [WrathChaos/react-native-bouncy-checkbox#30]
Hey! I'm using your component as a custom react-hook-form connected component and I'm wondering if there's a way that i can trigger the onPress by clicking on label text? The way i have it set up the checkbox color is changing but the animation and checkbox aren't showing. 

Thank you! The checkbox is really nice 💖

**Comment by ScottHenshaw86** [comment]
I'm also interested in this. I'd like to be able to add a 'Check All' and 'Uncheck All' buttons, but I can't get the checkboxes to display the checkmark this way. 
Otherwise this is a fantastic checkbox component. Thank you!

**Comment by WrathChaos** [comment]
I will work on it this week :) PR's are also welcome

**Comment by Sunhat** [comment]
Hi guys

You can toggle the isChecked prop with variable, then also set a checkboxVisible boolean, and hide the checkbox at the same time with this. When the component updates, set checkboxVisible back to true, and the component will re-render completely.

I do this to achieve the effect you're looking for. I'd provide my code, but I'm using vue-native

**Comment by WrathChaos** [comment]
Hello guys, 
@Sunhat , @ScottHenshaw86  and @bramirez96 

I've release a new version and make an example for synthetic press functionality and manual check state implementation. Please check it out: 

## [Release 2.1.0 🥳](https://github.com/WrathChaos/react-native-bouncy-checkbox/releases/tag/2.1.0)

**Comment by bramirez96** [comment]
Thank you so much! I'll check it out tomorrow, I'm very excited for this new functionality!!

**Comment by WrathChaos** [comment]
@bramirez96 Did you have a chance to test it out? I'm gonna close this issue depends on it
