### ISSUE TITLE
Checked text

### ISSUE THREAD

**Issue by talisonmarafiga** [WrathChaos/react-native-bouncy-checkbox#31]
Is it possible to change the color text when it is checked?

**Comment by WrathChaos** [comment]
Hello @talisonmarafiga,

Please check the new version: 
### [Version 2.0.0 is alive  🥳](https://github.com/WrathChaos/react-native-bouncy-checkbox/releases/tag/2.0.0)

You can set the text colour by using `textStyle` property and set the state with `onPress` functionality. If you cannot do it, please tell me and I can show you with a simple example :)

**Comment by fabyeah** [comment]
@WrathChaos I would like to see this example. Can't get it to work.
