### ISSUE TITLE
textColor not working on Android

### ISSUE THREAD

**Issue by Sunhat** [WrathChaos/react-native-bouncy-checkbox#32]
Hi, great package!

Just thought I'd mention textColor prop doesn't appear to be working on Android

```
      <BouncyCheckbox
        textColor="red"
        text="Task Completed"
      />
```

**Comment by WrathChaos** [comment]
Hello @Sunhat 
Thank you so much for reporting this. I will fix it ASAP. 

Most probably it will fix it on the fully refactored 1.5 version. I will inform you :)

**Comment by deathvendor** [comment]
I like the package, but the same problem is with borderColor, borderRadius ect...

**Comment by WrathChaos** [comment]
2.0 version is going to release today :) It will solve all of these problems, I will inform you.

**Comment by WrathChaos** [comment]
### [Version 2.0.0 is alive  🥳](https://github.com/WrathChaos/react-native-bouncy-checkbox/releases/tag/2.0.0)

Please open a new issue if you need something else :) @Sunhat @deathvendor
