### ISSUE TITLE
Enable/disable Automatic Strikethrough

### ISSUE THREAD

**Issue by seikosantana** [WrathChaos/react-native-bouncy-checkbox#33]
It is applying strikethrough automatically, but on some cases are not necessary

**Comment by WrathChaos** [comment]
Hello @seikosantana,

This issue is fixed on version 2.0.0 :) 

### [Version 2.0.0 is alive  🥳](https://github.com/WrathChaos/react-native-bouncy-checkbox/releases/tag/2.0.0)

**Comment by Sunhat** [comment]
@WrathChaos How do you disabled the strikethrough? I can't see it in the props or documentation for v2? Thanks!

**Comment by WrathChaos** [comment]
Hello @Sunhat,

Here is how to do it: 

```
<BouncyCheckbox
              isChecked
              text="Try new gym routine"
              textStyle={{
                fontFamily: "JosefinSans-Regular",
                color: "red",
                textDecorationLine: "none",
              }}
              onPress={(isChecked: boolean) => {}}
>
```

It is also available on the example as well :) You can customize almost anything if you cannot please open an issue and we can make it happen. Thank you

**Comment by Sunhat** [comment]
My bad! Thanks a lot!
