### ISSUE TITLE
ERROR  Warning: Failed prop type: Invalid props.style key `fill` supplied to `Text`

### ISSUE THREAD

**Issue by fazufi** [WrathChaos/react-native-bouncy-checkbox#332]
my code:
<BouncyCheckbox fillColor="#F8D000" .... />

I got this error:
ERROR  Warning: Failed prop type: Invalid props.style key `fill` supplied to `Text`.
Bad object: {
  "fill": "#F8D000",
  "textAlign": "center",
  "color": "#fff",
  "fontSize": 14,
  "lineHeight": 20,
  "fontWeight": "600",
  "letterSpacing": -0.25
}

**Comment by fazufi** [comment]
Hi, @WrathChaos 
I apologize, it turns out I was mistaken.
In my code, there is actually <Text fill="#F8D000" />
and it has no relation to the checkbox at all.

Thank you for your prompt response, and also thank you for react-native-bouncy-checkbox, which has been very helpful to me

Please, delete this issue, as it is not accurate

**Comment by WrathChaos** [comment]
Feel free to open an issue if you have awesome ideas :) 
Thank you for using the lib
