### ISSUE TITLE
Problem with the iconComponent prop not checking the checkbox state

### ISSUE THREAD

**Issue by ahmed-meraneh** [WrathChaos/react-native-bouncy-checkbox#336]
**Description**:

The iconComponent prop is supposed to allow rendering an icon based on the state of the checkbox, but it doesn't seem to check whether the checkbox is checked or not.

**Steps to Reproduce the Issue**:

```jsx
<BouncyCheckbox
    size={25}
    fillColor={Colors.primary}
    unfillColor="#FFFFFF"
    iconStyle={{ borderColor: Colors.primary, borderRadius: 4 }}
    disableText
    innerIconStyle={{ borderWidth: 2, borderRadius: 4 }}
    onPress={(isChecked: boolean) => {}}
    iconComponent={
      <Ionicons name="ios-checkmark" sfize={15} color="black" />
    }
  />
```

**Screenshot**: 

![WhatsApp Image 2023-09-12 at 10 45 10](https://github.com/WrathChaos/react-native-bouncy-checkbox/assets/94760825/b773e36c-5a18-4010-ac4f-2de6a1c7c882)

**Comment by WrathChaos** [comment]
Hello @ahmed-meraneh 

Since you're using a custom component for icons. The library itself cannot handle it, you should handle it by yourself. It should be easy tho since you already have access to `isChecked` or not.

**Comment by ahmed-meraneh** [comment]
Thank you
