### ISSUE TITLE
IMPROVE Add status props

### ISSUE THREAD

**Issue by melihmuratpesmen** [WrathChaos/react-native-bouncy-checkbox#38]
Hi @WrathChaos 
Can you add 'status' prop. İf u can add, we can  manage checkbox programmatically and manipulate without touch event is could be very usefull. Also with this prop checkbox can used as radioButton.

**Comment by WrathChaos** [comment]
Hello @melihmuratpesmen,

I believe that you can make it happen with the new version. Please check it out: 

## [Release 2.1.0 🥳](https://github.com/WrathChaos/react-native-bouncy-checkbox/releases/tag/2.1.0)

### [Documentation](https://github.com/WrathChaos/react-native-bouncy-checkbox#synthetic-press-functionality-with-manual-check-state)

You need to use `disableBuiltInState` prop and you need to make sure that `isChecked` prop is your new check state functionality now.

**Comment by melihmuratpesmen** [comment]
Thanks @WrathChaos,
Awesome feature 🚀🚀

**Comment by RodrigoSarmento** [comment]
> 

Why is this not the default?

**Comment by WrathChaos** [comment]
It's much easier to use with automatic handling. It's not easy to a ready-use checkbox if you need to handle its state. However, of course in some use-cases you need to handle yourself that's why I made it possible :)
