### ISSUE TITLE
controlled input

### ISSUE THREAD

**Issue by aprilmintacpineda** [WrathChaos/react-native-bouncy-checkbox#39]
It's better if we get the `checked` status from `props` instead of `state`.

I have a `Checkbox` that updates to checked or unchecked when certain conditions (coming from the backend) are met, but I can't do that with this library.

**Comment by WrathChaos** [comment]
Hello @aprilmintacpineda 

I believe that you can make it happen with the new version. Please check it out: 

## [Release 2.1.0 🥳](https://github.com/WrathChaos/react-native-bouncy-checkbox/releases/tag/2.1.0)

You need to use `disableBuiltInState` prop and you need to make sure that `isChecked` prop is your new check state functionality now.

**Comment by aprilmintacpineda** [comment]
Thanks @WrathChaos but I think the onPress is not working as expected anymore

https://github.com/WrathChaos/react-native-bouncy-checkbox/commit/09e21ca03608e61b787c87bf8a6414cc1182f08e#r49958499

**Comment by WrathChaos** [comment]
Hello @aprilmintacpineda,

Thank you for reporting. 
Actually when the dev set `disableBuiltInState` prop,  he/she should control the `check` state. That's why I did not re-pass the `isChecked` prop because it is already available with the local state.

**Comment by aprilmintacpineda** [comment]
Then I guess the docs is now misleading

![image](https://user-images.githubusercontent.com/21032419/116020052-1c89a080-a678-11eb-9a38-02c68aa7a8a2.png)

https://github.com/WrathChaos/react-native-bouncy-checkbox#synthetic-press-functionality-with-manual-check-state

**Comment by WrathChaos** [comment]
@aprilmintacpineda Awesome explanation! Actually, I really want to put it in the library's `onPress` passing however there can be some scenarios in which the dev wants to handle it on its own. However, yes doc is misleading I will update it.

**Comment by aprilmintacpineda** [comment]
Looks good to me, but I think someone looking at this the first time might not fully understand it. https://github.com/WrathChaos/react-native-bouncy-checkbox/pull/40

**Comment by WrathChaos** [comment]
Thank you so much @aprilmintacpineda, merged :)
