### ISSUE TITLE
Icons do not appear

### ISSUE THREAD

**Issue by Grishy** [WrathChaos/react-native-bouncy-checkbox#4]
Last version
![image](https://user-images.githubusercontent.com/13949080/71461551-464f6080-27c1-11ea-982f-4e12921a9b4c.png)

And in in console:
![image](https://user-images.githubusercontent.com/13949080/71461598-6da62d80-27c1-11ea-891b-c8da7903f191.png)

**Comment by Grishy** [comment]
I tried to run, but did not help
```bash
example git:(master) ✗ npm i react-native-vector-icons
example git:(master) ✗ npm i react-native-dynamic-vector-icons
```

**Comment by WrathChaos** [comment]
Let me test it :) Working on it

**Comment by WrathChaos** [comment]
@Grishy, I've tested the example inside of this library. Simply run this command: `rm -rf node_modules && rm -rf package-lock.json && npm install` and `react-native run-ios/android`. It works for me. If you still could not get it, please try to run this command also: `react-native link`

**Comment by WrathChaos** [comment]
@Grishy  I closed this issue.

**Comment by Grishy** [comment]
@WrathChaos 
`rm -rf node_modules && rm -rf package-lock.json && npm install and react-native run-android ` not work for me.

**Comment by WrathChaos** [comment]
Are you working on Android Emulator right?

**Comment by WrathChaos** [comment]
Check this out: https://github.com/oblador/react-native-vector-icons#android

**Comment by Grishy** [comment]
Ok i will try this evening

**Comment by Grishy** [comment]
> Are you working on Android Emulator right?
Yes. And on a real device, I also checked.

**Comment by WrathChaos** [comment]
You still could not get the icons? Actually this is about the `react-native-vector-icons` issue.
