### ISSUE TITLE
Dynamic styles

### ISSUE THREAD

**Issue by badalsaibo** [WrathChaos/react-native-bouncy-checkbox#401]
You see the inbuilt state functionality is great, but maybe we could also consider doing dynamic styles for all the styles received via props.

i.e

```js
<BouncyCheckbox
  iconStyle={(isChecked) => ({ borderColor: isChecked ? 'red' : 'blue' })}
/>
```

**Comment by WrathChaos** [comment]
Hello @badalsaibo 

You can customize anything for this library. 

You can customize the `iconStyle` but you should use the `isChecked` out side of the style itself.

**Comment by badalsaibo** [comment]
@WrathChaos Yeah. I was thinking of using that via built in state

**Comment by WrathChaos** [comment]
@badalsaibo You can do something like that

```tsx

const [checked, setChecked] = useState<boolean>(false);

<BouncyCheckbox
  text="Checkbox"
  iconStyle={{ borderColor: checked ? "red" : "blue" }}
  onPress={(isChecked: boolean) => { setChecked(isChecked); } }
/>
```
