### ISSUE TITLE
Distance between the icon and text?

### ISSUE THREAD

**Issue by lightning331** [WrathChaos/react-native-bouncy-checkbox#44]
How can I control the distance between the icon and text?

**Comment by WrathChaos** [comment]
Hello @lightning331 
The new version is available to customize the text container. Please try `textContainerStyle` prop to push the distance for the checkbox and the text.

### [Version 2.1.1](https://github.com/WrathChaos/react-native-bouncy-checkbox/releases/tag/2.1.1)

**Comment by lightning331** [comment]
Hello @WrathChaos 

Thanks for the fast reply. how should I style the textContainerStyle prop? 
Can you give me an example for that?

**Comment by WrathChaos** [comment]
Sure @lightning331 

```jsx
<BouncyCheckbox
   text="Call my mom 😇"
   textContainerStyle={{
         marginLeft: 32
    }}
   onPress={(checked: boolean) => {}}
/>
```

You can do such a thing :)
