### ISSUE TITLE
Can't show the checkmark

### ISSUE THREAD

**Issue by adrienfloor** [WrathChaos/react-native-bouncy-checkbox#45]
Hi, and thank you for the awesome library! Great work.

I can't seem to make the checkmark appear, I either have an empty round icon or a filled one, but never see the checkmark.

I'm using :
    "react-native-bouncy-checkbox": "^2.1.1",
    "react-native": "^0.62.2"
Here is my code : 
```jsx
<BouncyCheckbox
	isChecked={isReady}
	textStyle={{
		textDecorationLine: "none",
	}}
	size={25}
	fillColor="#0075FF"
	unfillColor="#FFFFFF"
	text="some text"
	iconStyle={{ borderColor: "#0075FF" }}
	onPress={() => {
		this.setState({
			isReady: !isReady
		})
	}}
/>
```
Would you have any idea what I'm doing wrong?
Thank you very much for your help !!!

**Comment by WrathChaos** [comment]
Hello @adrienfloor,
Can you try the example project?
Also, which version are you using on react-native-bouncy-checkbox?

**Comment by adrienfloor** [comment]
I'm using : 
"react-native-bouncy-checkbox": "^2.1.1"
😊

**Comment by adrienfloor** [comment]
Do you think I need react-native-vector-icons and all ?
Just so you know, it is working as expected when I build on iOS version 13.x.x but not on 14.x.x.
Thank you very much for your help !

**Comment by WrathChaos** [comment]
> Do you think I need react-native-vector-icons and all ?
> Just so you know, it is working as expected when I build on iOS version 13.x.x but not on 14.x.x.
> Thank you very much for your help !

You do not need react-native-vector-icons  library. Can you share the project with me because I cannot reproduce it with the example or any of my projects.

**Comment by adrienfloor** [comment]
My bad, updating react-native version made it work. Closing the issue, thank you very much for your help 🙌🏼

**Comment by WrathChaos** [comment]
If you need any other help, feel free to go :) 

Have fun! @adrienfloor
