### ISSUE TITLE
Add onLongPress action 

### ISSUE THREAD

**Issue by enieber** [WrathChaos/react-native-bouncy-checkbox#456]
I love this lib, thanks to create and mantainer.

I wanna request add onLongPress action to use to help add another actions.

**Comment by WrathChaos** [comment]
Nice one! I am completely rewrite the library, I will add this one. Thank you for suggesting

**Comment by WrathChaos** [comment]
Hello @enieber 

Finally I published the version 4 with longPress support, please check it out!


## [Version 4.0.0 🥳](https://github.com/WrathChaos/react-native-bouncy-checkbox/releases/tag/4.0.0)
