### ISSUE TITLE
TestID is not supported

### ISSUE THREAD

**Issue by nmehlei** [WrathChaos/react-native-bouncy-checkbox#459]
Hey,
First of all, thank you for the amazing checkbox control! 

One challenge that we are currently facing with the component is that the `testID` property does not seem to be supported by bouncy-checkbox. This is critical for end-to-end testing support.

Is this planned?

**Comment by WrathChaos** [comment]
Hello @nmehlei 

Thank you for kind words :) 

Actually I already have `{...this.props}` for the main `TouchableOpacity`. Do you think should I directly add `testID` as a property itself?

**Comment by WrathChaos** [comment]
Hello @nmehlei 

Version 4 is released! `testID` also supported directly, please try it out! 


## [Version 4.0.0 🥳](https://github.com/WrathChaos/react-native-bouncy-checkbox/releases/tag/4.0.0)
