### ISSUE TITLE
how can i change the distance between the check icon and the text

### ISSUE THREAD

**Issue by crowdn** [WrathChaos/react-native-bouncy-checkbox#51]
How can i change the distance between the check icon and the text. 
![image](https://user-images.githubusercontent.com/33209857/123552067-09459f00-d7a7-11eb-88d3-228a8b0b4198.png)

**Comment by WrathChaos** [comment]
https://github.com/WrathChaos/react-native-bouncy-checkbox/issues/49#issuecomment-863892905

Here is what you're looking for. 
```
textContainerStyle={{
    marginLeft: 32
}}
```

You can customize almost everything

**Comment by crowdn** [comment]
> [#49 (comment)](https://github.com/WrathChaos/react-native-bouncy-checkbox/issues/49#issuecomment-863892905)
> 
> Here is what you're looking for.
> 
> ```
> textContainerStyle={{
>     marginLeft: 32
> }}
> ```
> 
> You can customize almost everything

Thank you! it work to me. 'react-native-bouncy-checkbox' is a nice component.
