### ISSUE TITLE
If padding is used in style, some text seems to be 'squeezed out'

### ISSUE THREAD

**Issue by ziniuguo** [WrathChaos/react-native-bouncy-checkbox#52]
my code:
```javascript
<ScrollView style={{paddingHorizontal: 30}}>
    /* some code*/
    {this.state.list.map((item, index) => (
        <BouncyCheckbox
            /* something */
            key={index}
            text={some very long text}
        />
    )}
</ScrollView>
```

If i write paddingHorizontal, the text will be squeezed out.

![7LLTS I2E3$}XS)4~5NW1AS](https://user-images.githubusercontent.com/51998550/123916460-416dfd00-d9b4-11eb-8e5d-c1342173b07d.png)

How to solve this problem

Thanks in advance!

**Comment by ziniuguo** [comment]
I added paddingRight: 30 (same value as the ScrollView one) in the style of BouncyCheckbox, it works. Although idk why.

**Comment by WrathChaos** [comment]
Hello @ziniuguo 
I've never used such a long text. I need to test it.

**Comment by WrathChaos** [comment]
This has been fixed by @seyedmostafahasani

You can try it out with 4.0.1 version
