### ISSUE TITLE
isChecked value not being respected

### ISSUE THREAD

**Issue by alextbogdanov** [WrathChaos/react-native-bouncy-checkbox#529]
I have the following setup:

```
const [lookingForFilter, setLookingForFilter] = useState<lookingForFilterOption[]>(["shipmates"]);

// HANDLE LOOKING FOR SELECT
const handleLookingForSelect = (lookingFor: lookingForFilterOption) => {
  setLookingForFilter((prevLookingFor) => {
    if (prevLookingFor.length === 1 && prevLookingFor.includes(lookingFor)) {
      // Do not allow to unselect the last looking for option
      return prevLookingFor;
    }

    if (prevLookingFor.includes(lookingFor)) {
      // Remove the selected looking for if it's already in the array
      return prevLookingFor.filter((loo) => loo !== lookingFor);
    } else {
      // Add the selected looking for if it's not in the array
      return [...prevLookingFor, lookingFor];
    }
  });
};

<BouncyCheckbox
  size={30}
  fillColor={COLORS["primary"]}
  unFillColor="#FFFFFF"
  innerIconStyle={{ borderWidth: 2 }}
  isChecked={lookingForFilter.includes("shipmates")}
  onPress={() => handleLookingForSelect("shipmates")}
/>
```

Here if you press the same checkbox twice the handleLookingForSelect method doesn't remove it from the lookingFor array which is a state variable. The problem is that even thought "shipmates" is still in the array isChecked goes to false and unchecks the box. I have tried everything from the documentation, including setting a ref but I can't seem to fix this.

Any suggestions?

Dependencies:
"react-native": "0.74.3",
"react-native-bouncy-checkbox": "^4.0.1",

**Comment by DTX-Elliot** [comment]
I have a similar problem. I'm trying to prevent the user from clicking on the checkbox under certain conditions but the isChecked property is only respected on initial render. After that, if a user presses the checkbox it will animate the toggle despite the value of isChecked remaining the same. For example:

`<BouncyCheckbox
    ref={bouncyCheckboxRef}
   isChecked={true} <-- despite hard locking this property, the checkbox will still toggle on and off when the user presses it
 />`


Would like to see the isChecked property override the internal logic for toggling

**Comment by WrathChaos** [comment]
Hello @alextbogdanov  and @DTX-Elliot 
First of all I apologize for extremely late action. 

I released [4.1.0](https://github.com/WrathChaos/react-native-bouncy-checkbox/releases/tag/4.1.0) version with the `useBuiltInState` prop and updated the README with how to use it. 

Simply we just need to `useBuiltInState={false}` and set your own state to `isChecked` prop and that's all. Please, please give me feedback if it is working or not. 

Thank you so much for the patience!

**Comment by DTX-Elliot** [comment]
Can confirm this works as intended now, thank you very much for the update @WrathChaos, great stuff

**Comment by WrathChaos** [comment]
@DTX-Elliot New version is available to break the breaking change 🤭 Please move to [4.1.2](https://github.com/WrathChaos/react-native-bouncy-checkbox/releases/tag/4.1.2)
