### ISSUE TITLE
TouchableWithoutFeedback change to Pressable

### ISSUE THREAD

**Issue by dancixx** [WrathChaos/react-native-bouncy-checkbox#55]
Do you plan to upgrade to the Pressable component?

**Comment by WrathChaos** [comment]
Hello @dancixx,

Sure, I haven't use the `Pressable` for now but I can upgrade it :)

**Comment by dancixx** [comment]
@WrathChaos 

It would be great. The react-native docs mention that devs prefer should use this component and really much better than the others. :)

**Comment by WrathChaos** [comment]
@dancixx 

[Release 2.1.3](https://github.com/WrathChaos/react-native-bouncy-checkbox/releases/tag/2.1.3) 

is available and you can use any Touchable component with the new prop: `TouchableComponent`

You can simply use 

```jsx
<BouncyCheckbox
     TouchableComponent={Pressable}
     text="Custom Checkbox with Pressable Component"
     onPress={(isChecked: boolean) => {}}
/>
```

**Comment by dancixx** [comment]
Awesome!!! Thanks. :)

**Comment by dancixx** [comment]
@WrathChaos thanks for the update. I think everything works for now what I had time to test for. :)

**Comment by WrathChaos** [comment]
@dancixx Love to hear that :) Thank you so much man
