### ISSUE TITLE
tslib is needed to work with Expo

### ISSUE THREAD

**Issue by Darkensses** [WrathChaos/react-native-bouncy-checkbox#58]
### How to reproduce:

- Create an expo projects an install the `react-native-bouncy-checkbox` component.
- Try to copy the code example to your projects.

**Expected Result**: You should see a checkbox in your device screen
**Actual Result**: The console prints an error saying `tslib could not be found within the project`

**Workaround**:
Installing the tslib package
```
npm i tslib

**Comment by WrathChaos** [comment]
Hello @Darkensses 
`tslib` is a Typescript helper library. It is a dev-dependency need. This is not a bug or something.
