### ISSUE TITLE
onPress Callback the Check Value

### ISSUE THREAD

**Issue by WrathChaos** [WrathChaos/react-native-bouncy-checkbox#6]
[@Grishy's request](https://github.com/WrathChaos/react-native-bottom-search-bar/issues/4#issuecomment-569006678)

I'm going to add this now and release a new version :)

**Comment by Grishy** [comment]
@WrathChaos you change everything very quickly, cool!
But I do not need quick changes, so you can do as you like on time)

**Comment by WrathChaos** [comment]
Thank you @Grishy  :) That's okay, I would like to help you.

Please check this new release: 
# [Release: 0.0.5 🤩](https://github.com/WrathChaos/react-native-bouncy-checkbox/releases/tag/0.0.5)
