### ISSUE TITLE
Text is not visible

### ISSUE THREAD

**Issue by EKOLX** [WrathChaos/react-native-bouncy-checkbox#634]
Hello,

The issue is that these checkboxes inside `View` with style `flexDirection: 'row'` and text does not fit into one row. 
Is there any option like `Text` has `adjustsFontSizeToFit`?
And how decrease space between checkbox and text? 

```
<BouncyCheckbox
  isChecked={isIncome}
  text={translator.income}
  textStyle={styles.checkboxText}
  fillColor={Colors.main.blue}
  onPress={() => onCheckboxPress(!isIncome, false, false)}
/>
<BouncyCheckbox
  isChecked={isExpense}
  text={translator.expense}
  textStyle={styles.checkboxText}
  fillColor={Colors.main.red}
  onPress={() => onCheckboxPress(false, !isExpense, false)}
/>
<BouncyCheckbox
  isChecked={isAll}
  text={translator.all}
  textStyle={styles.checkboxText}
  fillColor={Colors.main.green}
  onPress={() => onCheckboxPress(false, false, !isAll)}
/>
```

`... checkboxText: {
    textDecorationLine: 'none',
  }, ...`

<img width="328" alt="Screenshot 2024-11-03 at 02 52 49" src="https://github.com/user-attachments/assets/d8e5ae18-240e-4cb9-9e80-f9efbf0251f1">

**Comment by WrathChaos** [comment]
Hello @EKOLX 
You do not need to use the Text itself inside the library. You can use `textComponent` prop to set your own Text. 

Example:

```tsx
<BouncyCheckbox
  isChecked={isAll}
  text={translator.all}
  textStyle={styles.checkboxText}
  fillColor={Colors.main.green}
  onPress={() => onCheckboxPress(false, false, !isAll)}
  textComponent={
      <Text adjustsFontSizeToFit>{translator.all}</Text>
  }
/>
```

**Comment by EKOLX** [comment]
> Hello @EKOLX You do not need to use the Text itself inside the library. You can use `textComponent` prop to set your own Text.
> 
> Example:
> 
> ```tsx
> <BouncyCheckbox
>   isChecked={isAll}
>   text={translator.all}
>   textStyle={styles.checkboxText}
>   fillColor={Colors.main.green}
>   onPress={() => onCheckboxPress(false, false, !isAll)}
>   textComponent={
>       <Text adjustsFontSizeToFit>{translator.all}</Text>
>   }
> />
> ```

Thank you

**Comment by omerts** [comment]
@WrathChaos textComponent works around  the issue, but the text prop still dosn't work with more recent react native versions including latest one. The textContainerStyle, and textStyle also do not work. I used the textComponent, but i am unable to vertically align my text.

**Comment by WrathChaos** [comment]
Hey @omerts 

Can you show me what you're trying to achieve and what version of react-native and this library you're using?

**Comment by omerts** [comment]
@WrathChaos 
Hi,
Using react-native 0.76.4 (but also tried on 0.76.0).
This lib version: ^4.1.2

Just a simple use case of text doesn't work:
```
<BouncyCheckbox
    text="test"
/>
 ```

**Comment by omerts** [comment]
@WrathChaos 
Hi,
Using react-native 0.76.4 (but also tried on 0.76.0).
This lib version: ^4.1.2

Just a simple use case of text doesn't work:
```
<BouncyCheckbox
    text="test"
/>
 ```

**Comment by WrathChaos** [comment]
I will take a look at this today! @omerts will back to you soon, thank you for reporting.

**Comment by WrathChaos** [comment]
Hey again @omerts sorry for late response.
I updated the example react native version to `0.76.4`  and test it out. It seems everything working. Can you please try it?

https://github.com/WrathChaos/react-native-bouncy-checkbox/tree/master/example

Feel free to open another issue if it still does not work for you.
