### ISSUE TITLE
Check png is not found

### ISSUE THREAD

**Issue by itsramiel** [WrathChaos/react-native-bouncy-checkbox#65]
I am using the package with with typescript template and here are is my dependency list:
"@react-navigation/bottom-tabs": "^6.0.7",
    "@react-navigation/native": "^6.0.4",
    "@react-navigation/native-stack": "^6.2.2",
    "expo": "~42.0.1",
    "expo-status-bar": "~1.0.4",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz",
    "react-native-big-list": "^1.4.3",
    "react-native-bouncy-checkbox": "^2.1.6",
    "react-native-gesture-handler": "~1.10.2",
    "react-native-google-places-autocomplete": "^2.4.1",
    "react-native-safe-area-context": "3.2.0",
    "react-native-screens": "~3.4.0",
    "react-native-web": "~0.13.12",
    "swr": "^1.0.1",
    "tslib": "^2.3.1"

However I am getting the following error:
`
iOS Bundling failed 5245ms
Unable to resolve module ./check.png from C:\Users\thesk\Desktop\react-native\cleverProgrammer\ubereats\node_modules\react-native-bouncy-checkbox\build\dist\BouncyCheckbox.js:

None of these files exist:
  * check.png
  * node_modules\react-native-bouncy-checkbox\build\dist\check.png\index(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json)
   5 | const react_native_1 = require("react-native");
   6 | const BouncyCheckbox_style_1 = (0, tslib_1.__importStar)(require("./BouncyCheckbox.style"));
>  7 | const defaultCheckImage = require("./check.png");
     |                                    ^
   8 | class BouncyCheckbox extends React.Component {
   9 |     constructor(props) {
  10 |         super(props);
`

**Comment by ramiel1999** [comment]
chech.png is missing from the build/dist
