### ISSUE TITLE
unable to build react-native-vector-icons 9.0.0

### ISSUE THREAD

**Issue by lukasa1993** [WrathChaos/react-native-bouncy-checkbox#73]
```
error An unexpected error occurred: "could not find a copy of react-native-vector-icons to link in /Users/test/node_modules/react-native-bouncy-checkbox/node_modules".
```

using "react-native-bouncy-checkbox": "^2.1.7"

problem with "react-native-vector-icons": "9.0.0" works with 8.1.0

**Comment by WrathChaos** [comment]
Hello,
Let me test it very fast with the vector-icons v9. 
Thank you for the reporting this issue :)

**Comment by lukasa1993** [comment]
ios

**Comment by WrathChaos** [comment]
Hey again @lukasa1993,

It also works on iOS as well. Try to remove your `node_modules` and `Pods.lock` files. 

Then try to run `npm i && npx pod-install` 

It should work, also there is no dependency to use the library.

**Comment by lukasa1993** [comment]
i tried but will try again

**Comment by chaosLegacy** [comment]
I'm facing the same issue on expo running under android device
Downgrading react-native-vector-icons to 8.1.0 seems to fix the issue

**Comment by WrathChaos** [comment]
There is no dependency on the react-native-vector-icons on this library. Probably this is the react-native-vector-icons' problem.

**Comment by lukasa1993** [comment]
> There is no dependency on the react-native-vector-icons on this library. Probably this is the react-native-vector-icons' problem.

its in peer-dependency

  "peerDependencies": {
    "react": ">= 16.x.x",
    "react-native": ">= 0.55.x",
    "react-native-vector-icons": ">= 6.6.0",
    "react-native-dynamic-vector-icons": ">= 0.2.1"
  },

**Comment by WrathChaos** [comment]
> > There is no dependency on the react-native-vector-icons on this library. Probably this is the react-native-vector-icons' problem.
> 
> its in peer-dependency
> 
> ```
>   "peerDependencies": {
>     "react": ">= 16.x.x",
>     "react-native": ">= 0.55.x",
>     "react-native-vector-icons": ">= 6.6.0",
>     "react-native-dynamic-vector-icons": ">= 0.2.1"
>   }
> ```


Forgot to remove them, I will remove them now. Thank you for let me know :)

**Comment by WrathChaos** [comment]
Hello again @lukasa1993, @chaosLegacy 

I published the [2.1.8](https://github.com/WrathChaos/react-native-bouncy-checkbox/releases/tag/2.1.8) version. 

Peer dependencies are removed and better tsconfig is here with the `tslib` dependency is no longer exist :)

**Comment by lukasa1993** [comment]
thank you 👍

**Comment by WrathChaos** [comment]
@lukasa1993 Can you please tell me if there is still a problem with `react-native-vector-icon` v9?

**Comment by lukasa1993** [comment]
> @lukasa1993 Can you please tell me if there is still a problem with `react-native-vector-icon` v9?

it works with V9 now with ` "react-native-bouncy-checkbox": "^2.1.8",` 👍
