### ISSUE TITLE
Migrate to react-native-reanimated

### ISSUE THREAD

**Issue by dancixx** [WrathChaos/react-native-bouncy-checkbox#83]
Do you plan to migrate to the RN-Reanimated 2? Sometimes the check animation is freezing when the JS Thread is full.

**Comment by WrathChaos** [comment]
Hello @dancixx,

I actually really want to improve the bouncing logic and replace the react-native Animated one with reanimated 2 however I'm thinking about the dependency problem. What do you think about that?

**Comment by dancixx** [comment]
I can understand your dilemma in the case of zero dependencies but for example, I use Reanimated2 everywhere and I think much more future forwarded like react-native animated API, by the way, you have access to the threads and the animations are much smoother and the new Reanimated 2 has support for 120 fps animations. I thought for a long time that I can avoid the Reanimated 2 but in bigger projects much better like the inbuilt API, but if you want to hold the library without any dependency then I can create a forked version with Reanimated 2 and function components.

**Comment by WrathChaos** [comment]
Maybe I can create another library with the reanimated 2, I love the library itself but zero dependencies is really cool to use. We also need to think about the other devs too. Probably another library and mentioning it on the README is a much better idea.

**Comment by mohammedelnady** [comment]
please don't migrate to reanimated it has many issues during debugger

**Comment by WrathChaos** [comment]
Hello @mohammedelnady,
I will re-write the `react-native-bouncy-checkbox` with reanimated v2 but on another separated library. You can still use this without any issue don't worry :)

**Comment by mohammedelnady** [comment]
thanks man

**Comment by WrathChaos** [comment]
We can continue with this issue: #90
