### ISSUE TITLE
Passing custom text component throws an error in TypeScript

### ISSUE THREAD

**Issue by dmahajan980** [WrathChaos/react-native-bouncy-checkbox#84]
Whenever a custom component is passed to the `textComponent` prop, TypeScript throws the following error:

<img width="713" alt="Screenshot 2022-01-05 at 9 25 28 PM" src="https://user-images.githubusercontent.com/37256767/148248467-3ac8fe2c-51d2-461d-8edb-c45a9477324c.png">

Stack details:
Expo SDK 44.0.0
React Native v0.64.3
React v17.0.1
TypeScript v4.3.5

**Comment by WrathChaos** [comment]
Hello @dmahajan980 
Thank you so much for reporting this. 

I will fix it now :)

**Comment by WrathChaos** [comment]
Hello again @dmahajan980 

I think I fixed it and fixed many more. 

Can you please try the new release: [2.1.10](https://github.com/WrathChaos/react-native-bouncy-checkbox/releases/tag/2.1.10)

**Comment by dmahajan980** [comment]
Hi @WrathChaos, thanks for resolving this so quickly! Seems that the latest version (2.1.10) isn't published on NPM yet. I'll try this later tomorrow while NPM publishes this.

**Comment by WrathChaos** [comment]
@dmahajan980 
I guess it is published now. If you have time, can you try it?

**Comment by dmahajan980** [comment]
@WrathChaos I tried this and everything seems to work perfectly. Thank you so much for quickly fixing this bug 😊

**Comment by dmahajan980** [comment]
@WrathChaos 
Also, is it possible to change the color of default check icon? I can't get it changed without using a custom icon.

**Comment by WrathChaos** [comment]
@dmahajan980

You can use iconImageStyle with tintColor style :)
