### ISSUE TITLE
Disable checkbox image 

### ISSUE THREAD

**Issue by alexisbl14** [WrathChaos/react-native-bouncy-checkbox#97]
Hi WrathChaos, 
Is there a way to disable the checkbox image entirely and just have a filled in box when it is "checked"? 

Thanks!

**Comment by WrathChaos** [comment]
Hello @alexisbl14 
Thank you for writing.

You can use `iconComponent` for disabling the image completely
```jsx
<BouncyCheckbox 
    iconComponent={null}
    onPress={(isChecked: boolean) => {}} 
/>
```

Something like this :)
