### ISSUE TITLE
Toggling the checkboxes is not working when calling a function within the handelOnPress function!

### ISSUE THREAD

**Issue by husseinmansour6** [WrathChaos/react-native-bouncy-checkbox#98]
Hey @WrathChaos ,

I have a `Flatlist` that has some BouncyCheckbox components. 

```
 const handelWorkToDo = (service, isChecked) => {
    if (isChecked) {
      console.log('add service');
      setWorkToDo([...workToDo, service]);
    } else {
      console.log('remove service');
      const isAvailable = (item) => item.id === service.id;
      R.filter(isAvailable, workToDo);
    }
  };

const Service = ({ id, title, duration }) => (
    <BouncyCheckbox
      fillColor="red"
      iconStyle={{ borderColor: 'red' }}
      key={id}
      onPress={(isChecked) =>
        handelWorkToDo({ id, title, duration }, isChecked)
      }
      style={{ paddingBottom: 10 }}
      text={`${title} -> ${duration}`}
      textStyle={{
        textDecorationLine: 'none',
      }}
    />
  );

const renderItem = ({ item }) => <Service {...item} />;

<FlatList
        data={DATA}
        renderItem={renderItem}
        keyExtractor={(item) => item.id}
        style={{ padding: 2 }}
/>


```

Whats happening is that when when I call the `setWorkToDo([...workToDo, service])` or `R.filter(isAvailable, workToDo)` within the `handelWorkToDo` function, checkbox state is not being changed. 

however if I remove/comment out those functions, the checkboxes are being checked without issues.

I would like to know if there is something missing within my code or If you have a fix for that. 

Thank you :)

**Comment by WrathChaos** [comment]
Hello @husseinmansour6 
Thank you for reaching me and using this library :) 

I guess you need to set a manual state instead of built-in state system.
Please take a look at the [Manual Check State](https://github.com/WrathChaos/react-native-bouncy-checkbox#synthetic-press-functionality-with-manual-check-state)

**Comment by husseinmansour6** [comment]
Hey @WrathChaos ,

Thanks for the quick reply! 

I had to do some work around for it to work as expected however it would be nice to support that within ur lib. 

I took a look into the Manual check state and I saw that you are using one checkbox to toggle on/off with a useState hook. It would be nice to have an example of using multiple checkboxes that can toggle them with useState hook.

Thank you :)

**Comment by WrathChaos** [comment]
@husseinmansour6 glad to hear that you can make it work :) 

I will try to make an example for multiple checkboxes with manual state but if you would like to contribute to library. I'll love to add the example with your use-cases as well :) It will surely help other people as well

**Comment by husseinmansour6** [comment]
@WrathChaos yeah sure I would love to share my approach and you decide whether you keep it or find a better way. 
Do i need to get access in order to contribute?

**Comment by WrathChaos** [comment]
@husseinmansour6 
Nope, you can make a fork or if you want you can share it in here or make a gist and we can add as a separate documentation.

**Comment by husseinmansour6** [comment]
@WrathChaos Hey again, I forked the repo and tried to run it and I got some issues. Do you have a documentation on how to run it or could you please explain it briefly here?

**Comment by WrathChaos** [comment]
> 

Hello again,
Sorry for late response.
What do you mean by the issues? Are you trying to run the `example` or `example-manuel-state`?

**Comment by husseinmansour6** [comment]
Yeah Im trying to run the example one. should I run a different one?

**Comment by husseinmansour6** [comment]
okay I'll try again and let you know

**Comment by husseinmansour6** [comment]
So, I was able to run it and just created a PR for my changes. Please take a look [here](https://github.com/WrathChaos/react-native-bouncy-checkbox/pull/102) and let me know your thoughts :)

**Comment by husseinmansour6** [comment]
@WrathChaos any updates?

**Comment by WrathChaos** [comment]
Hey @husseinmansour6 Really sorry for late response. I will take a look at it today. Extremely busy days
